language: cpp
compiler:
  - clang
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglm-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libstdc++-7-dev
before_script:
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release  
script:
- cmake --build build
